# -*- coding: utf-8 -*-
"""Concentraciones.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ac07qwRXMtNw9tSVkJw2WnnDx9uMvcNU

# Concentraciones
"""

#Ingreso de librerias a usar
from numpy import *
import pandas as pd

tabla = pd.DataFrame(index=range(7), columns=range(3))
tabla.iloc[0,0] = "sustancia"
tabla.iloc[0,1] = "Fluido"
tabla.iloc[0,2] = "ppm"

tabla.iloc[1,0] = "Floculante"
tabla.iloc[1,1] = "Agua"
tabla.iloc[1,2] = "50"

tabla.iloc[2,0] = "Biocida"
tabla.iloc[2,1] = "Agua"
tabla.iloc[2,2] = "500-1000"

tabla.iloc[3,0] = "Antiescal"
tabla.iloc[3,1] = "Agua"
tabla.iloc[3,2] = "30"

tabla.iloc[4,0] = "Clarificador"
tabla.iloc[4,1] = "Agua"
tabla.iloc[4,2] = "50"

tabla.iloc[5,0] = "Secuestrante de oxigeno"
tabla.iloc[5,1] = "Fluido"
tabla.iloc[5,2] = "10"

tabla.iloc[6,0] = "Desmulsificante"
tabla.iloc[6,1] = "Oil"
tabla.iloc[6,2] = "35"

print(tabla)

#Ingreso de los datos
BFPD=float(input("Ingrese el caudal del fluido: "))
agua=float(input("Ingrese el porcentaje de agua(fracción): "))
d=float(input("Ingrese el diametro del flow line: "))
L=float(input("Ingrese la longitud del flow line: "))
ppm=float(input("Ingrese las partes por millon: "))
B=float(input("Ingrese el tiempo del bache(hr): "))
s=float(input("Seleccione una sustancia en orden de la tabla(1-6): "))

#Calculos
BWPD=BFPD*agua
BOPD=BFPD-BWPD

#solución
if s==1:
  qw=(BWPD*B)/24
  gal=qw*42
  res=(gal*ppm)/(1*10**6-ppm)
  print("Se debe usar ",res," gal de floculante al enviar al PIG")
if s==2:
    qw=(BWPD*B)/24
    gal=qw*42
    res=(gal*ppm)/(1*10**6-ppm)
    print("Se debe usar ",res," gal de biocida al enviar al PIG")
if s==3:
    qw=(BWPD*B)/24
    gal=qw*42
    res=(gal*ppm)/(1*10**6-ppm)
    print("Se debe usar ",res," gal de antiescal al enviar al PIG")
if s==4:
    qw=(BWPD*B)/24
    gal=qw*42
    res=(gal*ppm)/(1*10**6-ppm)
    print("Se debe usar ",res," gal de clarificador al enviar al PIG")
if s==5:
    qw=(BFPD*B)/24
    gal=qw*42
    res=(gal*ppm)/(1*10**6-ppm)
    print("Se debe usar ",res," gal de secuestrante de oxigeno al enviar al PIG")
if s==6:
    qw=(BOPD*B)/24
    gal=qw*42
    res=(gal*ppm)/(1*10**6-ppm)
    print("Se debe usar ",res," gal de desmulsificante al enviar al PIG")


Q=BFPD*5.615/3600
A=pi*d**2/4
v=Q/A
print("Llega con ",v," ft^3/s al PIG")
t=A*L/Q
print("Llega con ",t," s al PIG")