# -*- coding: utf-8 -*-
"""PrecioPetróleo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12MpEvpkySuunW5FSQD724M4cskulZzuz

# Tendencia Petróleo
"""

import pandas as pd
import matplotlib.pyplot as plt
from pandas import DataFrame
#Hacemos un llamado al exel, donde contiene los precios historicos del petroleo
#de 10 años.
precio_petroleo=pd.read_excel("/content/Datos históricos Futuros petróleo crudo WTI 10 años.xlsx")
precio_petroleo
#Observamos como se crea una tabla con todos los datos
df=DataFrame(precio_petroleo)
df

#Procedemos a realizar una tendencia
fig,ax=plt.subplots(figsize=(14,10))
ax.plot(precio_petroleo["Fecha"],precio_petroleo["Último"],marker="^",
        label='Últimos precios')
ax.plot(precio_petroleo["Fecha"],precio_petroleo["Apertura"],
        color="tab:green",marker="o", label='Precios de apertura')
ax.invert_xaxis()
ax.set_xticks(range(1,132,12))
ax.set_title("Tendencia de los precios del petróleo",loc="center",fontdict=
             {"fontsize":15,"fontweight":"bold"})
ax.set_xlabel("Fecha",fontdict={"fontsize":14,"fontweight":"bold","color":"tab:blue"})
ax.set_ylabel("Precio",fontdict={"fontsize":14,"fontweight":"bold","color":"tab:blue"})
plt.legend(loc='lower left',fontsize="large")

#Realizamos un diagrama de dispersión con la relación de los valores mínimos
#Y máximos
df.plot(title="Diagrama de dispersión precios",x='Máximo',y="Mínimo",kind='scatter',figsize=(14,10))
plt.show